version: '3.8'

services:
  db:
    image: postgres:13
    container_name: real_estate_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: estatedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - real_estate_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real_estate_service
    environment:
      CONFIG_PATH: /real-estate-service/config/docker.yaml
      DATABASE_URL: postgres://myuser:pass@db:5432/estatedb
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - real_estate_network

networks:
  real_estate_network:
    driver: bridge

volumes:
  postgres_data:
